FROM registry.redhat.io/rhbk/keycloak-rhel9:26.2 AS builder

# it's manadatory to enable these variables in the build stage and delete them from the CR of keycloak
ENV KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true \
    KC_TRACING_ENABLED=true \
    KC_TRACING_ENDPOINT='http://tempo-sample-distributor.tempo.svc.cluster.local:4317' \
    KC_DB=postgres

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
ADD --chmod=644 ./keycloak-franceconnect-7.5.0.jar /opt/keycloak/providers/keycloak-franceconnect-7.5.0.jar
RUN /opt/keycloak/bin/kc.sh build


FROM registry.redhat.io/rhbk/keycloak-rhel9:26.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/


ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]