apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
#  image: quay.io/rh_ee_blandols/test-keycloak/rhbk26:amd64-latest
  imagePullSecrets:
    - name: 11009103-----pull-secret
#    - name: rh-ee-blandols-pull-secret
  # To configure the Keycloak initial admin user
  bootstrapAdmin:
    user:
      secret: initial-admin-secret
  db:
    database: keycloak
    host: postgresdb-primary.kc-pg-database.svc.cluster.local
    passwordSecret:
      key: password
      name: keycloak-db-secret
    port: 5432
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
    # To configure the database pool size 
    #poolInitialSize: 5
    #poolMinSize: 10
    #poolMaxSize: 20
  hostname:
  # example without /auth path
    hostname: https://keycloak.apps.cluster-g9zwl.g9zwl.sandbox1850.opentlc.com
#    hostname: https://keycloak.apps.cluster-g9zwl.g9zwl.sandbox1850.opentlc.com/auth
  # example without /auth path
    admin: https://kc-admin.apps.cluster-g9zwl.g9zwl.sandbox1850.opentlc.com
#    admin: https://kc-admin.apps.cluster-g9zwl.g9zwl.sandbox1850.opentlc.com/auth
    #strict: false
    # If all applications use the public URL this option should be enabled.
    strictBackchannel: true
  http:
    httpEnabled: true
    httpPort: 8080
    httpsPort: 8443
    # To configure the TLS secret
    #tlsSecret: my-tls-secret
  ingress:
    className: openshift-default
  # disable this feature if you don't want to use the ingress created by keycloak, in this case create you route manifest
    enabled: false
  instances: 3
  proxy:
    headers: xforwarded
  # To configure the truststore
  #truststores:
  #  my-truststore:
  #    secret:
  #      name: my-secret
  # To configure the other KC environment variables, the following is ignored in case of using a custom image
  additionalOptions:
    - name: metrics-enabled
      value: 'true'
    - name: health-enabled
      value: 'true'
    - name: tracing-enabled
      value: 'true'
    - name: tracing-endpoint
      value: 'http://tempo-sample-distributor.tempo.svc.cluster.local:4317'
    - name: http-management-relative-path
      value: /management
# Enable this parameter if you want to keep /auth in the path of hostname
#    - name: http-relative-path
#      value: /auth
  #  - name: spi-connections-http-client-default-connection-pool-size
  #    secret: # Secret reference
  #      name: http-client-secret # name of the Secret
  #      key: poolSize # name of the Key in the Secret
  #  - name: spi-email-template-mycustomprovider-enabled
  #    value: true # plain text value
  #  - name: example_env_var
  #    configMapFile
  #      name: my-configmap
  #      key: example
  resources:
    requests:
      cpu: 1
      memory: 1500Mi
    limits:
      cpu: 3
      memory: 3Gi
  # Configuration to mount volumes
  unsupported:
    podTemplate:
      metadata:
        annotations:
          checksum/kc-franceconnect-provider: "60f8b85d8326d55f74a464450f0c25e1feec53bbaa406194d32241ee5fe3a194" 
      spec:
        containers:
          - volumeMounts:
              - mountPath: /opt/keycloak/providers/keycloak-franceconnect-7.5.0.jar
                name: kc-franceconnect-provider
                subPath: keycloak-franceconnect-7.5.0.jar
              - mountPath: /opt/keycloak/providers/password-expiry-idm-1.0.0.jar
                name: custom-provider
                subPath: password-expiry-idm-1.0.0.jar
        volumes:
          - configMap:
              items:
                - key: keycloak-franceconnect-7.5.0.jar
                  path: keycloak-franceconnect-7.5.0.jar
              name: kc-franceconnect-provider
            name: kc-franceconnect-provider
          - configMap:
              items:
                - key: password-expiry-idm-1.0.0.jar
                  path: password-expiry-idm-1.0.0.jar
              name: custom-provider
            name: custom-provider
  # Configure scheduling, affinity, tolerations, and topologySpreadConstraints
  #scheduling:
  #  priorityClassName: custom-high
  #  affinity:
  #    podAffinity:
  #      preferredDuringSchedulingIgnoredDuringExecution:
  #      - podAffinityTerm:
  #          labelSelector:
  #            matchLabels:
  #              app: keycloak
  #              app.kubernetes.io/managed-by: keycloak-operator
  #              app.kubernetes.io/component: server
  #              topologyKey: topology.kubernetes.io/zone
  #            weight: 10
  #  tolerations:
  #  - key: "some-taint"
  #    operator: "Exists"
  #    effect: "NoSchedule"
  #  topologySpreadConstraints:
  #  - maxSkew: 1
  #    topologyKey: kubernetes.io/hostname
  #    whenUnsatisfiable: DoNotSchedule
