apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpasswd
      mappingMethod: claim
      name: htpasswd_provider
      type: HTPasswd
    - name: keycloak 
      mappingMethod: claim 
      type: OpenID
      openID:
        clientID: openshift-console 
        clientSecret: 
          name: keycloak-idp-secret
        claims: 
          preferredUsername:
          - preferred_username
          name:
          - name
          email:
          - email
          groups:
          - groups
        issuer: https://www.idp-issuer.com 

