apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-keycloak-viewers
  namespace: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  name: keycloak-viewers
  apiGroup: rbac.authorization.k8s.io