apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgresdb
  namespace: keycloak
spec:
  openshift: true
  postgresVersion: 16
  instances:
    - name: kc-db
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  users:
    - name: keycloak
      options: "SUPERUSER"
      databases:
        - keycloak
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "host all all 0.0.0.0/0 md5" # This is too open, only used in this demo, never for production
          - "local all all trust" # This is too open, only used in this demo, never for production
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi
