apiVersion: v1
kind: Secret
metadata:
  name: postgresdb-pguser-keycloak
  namespace: keycloak
  labels:
    postgres-operator.crunchydata.com/cluster: postgresdb
    postgres-operator.crunchydata.com/pguser: keycloak
type: Opaque
stringData:
  password: a2V5Y2xvYWs= #(keycloak)