apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: aprr
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: Grafana
    repoURL: 'https://github.com/BechirLandolsi/rhbk26.git'
    targetRevision: HEAD
