apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: openshift-gitops
spec:
  destination:
    namespace: keycloak
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: rhbk26/GitOps/rhbk-helm
    repoURL: 'https://github.com/BechirLandolsi/rhbk26.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml