{{- /* -------- derive http-relative-path; default "/" -------- */ -}}
{{- $hr := dict "val" "/" -}}
{{- $ao := .Values.keycloak.additionalOptions | default dict -}}
{{- if and $ao.enabled $ao.options }}
  {{- range $ao.options }}
    {{- if eq .name "http-relative-path" }}
      {{- $v := trimAll " " .value -}}
      {{- if or (eq $v "") (eq $v "/") }}
        {{- $_ := set $hr "val" "/" -}}
      {{- else }}
        {{- $_ := set $hr "val" (printf "/%s" (trimAll "/" $v)) -}}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{- /* -------- derive management path; default "/" -------- */ -}}
{{- $mp := dict "val" "/" -}}
{{- if and $ao.enabled $ao.options }}
  {{- range $ao.options }}
    {{- if eq .name "http-management-relative-path" }}
      {{- $v := trimAll " " .value -}}
      {{- if or (eq $v "") (eq $v "/") }}
        {{- $_ := set $mp "val" "/" -}}
      {{- else }}
        {{- $_ := set $mp "val" (printf "/%s" (trimAll "/" $v)) -}}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{- /* -------- join http-relative-path + management path -------- */ -}}
{{- $joined := dict "val" "/" -}}
{{- if eq $hr.val "/" }}
  {{- $_ := set $joined "val" $mp.val -}}
{{- else }}
  {{- if or (eq $mp.val "/") (eq $mp.val "") }}
    {{- $_ := set $joined "val" $hr.val -}}
  {{- else }}
    {{- $_ := set $joined "val" (printf "%s/%s" $hr.val (trimPrefix "/" $mp.val)) -}}
  {{- end }}
{{- end }}

{{- /* -------- host from hostname.admin (strip scheme) -------- */ -}}
{{- $rawAdmin := (default "" .Values.keycloak.hostname.admin) -}}
{{- $adminHost := (regexReplaceAll "^https?://([^/]+).*" $rawAdmin "$1") -}}

{{- if and $adminHost .Values.keycloak.routeManagement.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.keycloak.routeManagement.name | default (printf "%s-management" (include "rhbk.fullname" .)) }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  host: {{ $adminHost | quote }}
  {{- if ne $joined.val "/" }}
  path: {{ $joined.val | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.keycloak.routeManagement.serviceName | default (include "rhbk.fullname" .) }}
    weight: 100
  port:
    targetPort: {{ .Values.keycloak.routeManagement.targetPort | default "management" | quote }}
  {{- with .Values.keycloak.routeManagement.tls }}
  tls:
    termination: {{ .termination | default "edge" | quote }}
    {{- with .insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ . | quote }}
    {{- end }}
  {{- end }}
  wildcardPolicy: {{ .Values.keycloak.routeManagement.wildcardPolicy | default "None" | quote }}
{{- end }}
