{{- /* -------- derive management path ONLY (ignore http-relative-path) -------- */ -}}
{{- $mp := dict "val" "/management" -}}
{{- $ao := .Values.keycloak.additionalOptions | default dict -}}

{{- if and $ao.enabled $ao.options }}
  {{- range $ao.options }}
    {{- if eq .name "http-management-relative-path" }}
      {{- $v := trimAll " " .value -}}

      {{- if or (eq $v "") (eq $v "/") }}
        {{- $_ := set $mp "val" "/" -}}
      {{- else }}
        {{- $_ := set $mp "val" (printf "/%s" (trimAll "/" $v)) -}}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{- /* -------- get admin host (strip scheme) -------- */ -}}
{{- $rawAdmin := (default "" .Values.keycloak.hostname.admin) -}}
{{- $adminHost := (regexReplaceAll "^https?://([^/]+).*" $rawAdmin "$1") -}}

{{- if and $adminHost .Values.keycloak.routeManagement.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.keycloak.routeManagement.name | default (printf "%s-management" (include "rhbk.fullname" .)) }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  host: {{ $adminHost | quote }}

  {{- if ne $mp.val "/" }}
  path: {{ $mp.val | quote }}
  {{- end }}

  to:
    kind: Service
    name: {{ .Values.keycloak.routeManagement.serviceName | default (include "rhbk.fullname" .) }}
    weight: 100

  port:
    targetPort: {{ .Values.keycloak.routeManagement.targetPort | default "management" | quote }}

  {{- with .Values.keycloak.routeManagement.tls }}
  tls:
    termination: {{ .termination | default "edge" | quote }}
    {{- with .insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ . | quote }}
    {{- end }}
  {{- end }}

  wildcardPolicy: {{ .Values.keycloak.routeManagement.wildcardPolicy | default "None" | quote }}
{{- end }}
