kind: Secret
apiVersion: v1
metadata:
  name: keycloak-db-secret
  namespace: keycloak
data:
  username: a2V5Y2xvYWs= #(keycloak)
  password: eUkxQ3FLMyh8U1JNcTh8cCxydnRyaHp8Cg== #(yI1CqK3(|SRMq8|p,rvtrhz|) 
type: Opaque