apiVersion: v1
kind: Secret
metadata:
  name: tempostack-dev-minio
  namespace: tempo         # <- your namespace
stringData:
  endpoint: http://minio-service.minio.svc.cluster.local:9000   # or your Route URL
  bucket: keycloak                                  # must exist in MinIO
  access_key_id: minio
  access_key_secret: minio123
type: Opaque
